-- AlterTable
ALTER TABLE "issue_fields" ALTER COLUMN "type" SET DATA TYPE VARCHAR(20);

-- AlterTable
ALTER TABLE "issue_states" ALTER COLUMN "name" SET DATA TYPE VARCHAR(30),
ALTER COLUMN "type" SET DATA TYPE VARCHAR(20);

-- AlterTable
ALTER TABLE "issue_types" ALTER COLUMN "type" SET DATA TYPE VARCHAR(20);

-- AlterTable
ALTER TABLE "issues" ALTER COLUMN "type" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "state" SET DATA TYPE VARCHAR(30);

-- AlterTable
ALTER TABLE "projects" ALTER COLUMN "shortcode" SET DATA TYPE VARCHAR(6),
ALTER COLUMN "color" SET DATA TYPE VARCHAR(6);
