name: CI

on:
  pull_request:
    branches: [main, production]
  push:
    branches: [main, production]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: Hello
      INNGEST_EVENT_KEY: local
      ABLY_API_KEY: test
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 18.15.0
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install JS dependencies (workspace)
        run: |
          npm install
      - name: Build / Compile
        run: |
          npm run build
      - name: Run tests
        run: |
          npm run test
